# GitHub Profile Chat Configuration
# HTML-powered interactive chat interface

# Chat Behavior
chat:
  max_messages: 10            # Maximum messages to display
  title: "#readme-chat"       # Chat session title
  max_width: "600px"          # HTML container max width
  theme: "github"             # Styling theme

# Features
features:
  filter_bots: true           # Hide bot comments
  enable_timestamps: true     # Show message timestamps
  enable_avatars: true       # Show user profile avatars
  enable_reactions: true     # Show comment reactions with emojis
  human_friendly_time: true  # Use relative timestamps (e.g., '2 minutes ago')
  clickable_usernames: true   # Link usernames to GitHub profiles
  avatar_size: "32px"         # Avatar size (when enabled)

# API Configuration  
api:
  max_retries: 3              # GitHub API retry attempts
  retry_delay: 1.0            # Delay between retries (seconds)
  timeout: 30                 # Request timeout (seconds)

# Content Management
content:
  max_message_length: 500     # Truncate very long messages
  max_lines_per_message: 6    # Lines before truncation
  sanitize_content: true      # Basic content sanitization
  smart_truncation: true      # Intelligent message trimming